import type { CampusDsaStage, CampusDsaProblem } from '@/types/technical';

export const CAMPUS_DSA_ROADMAP_STAGES: CampusDsaStage[] = [
  // ── STAGE 1: ARRAYS & TWO POINTERS ──────────────────────────────────────────
  {
    id: 'stage-1-two-pointers',
    stageNumber: 1,
    title: 'Stage 1: Arrays & Two Pointers',
    cluster: 'Pointers & Arrays',
    description: 'Master opposing pointers, sorted pairs, container geometry, and in-place three-way partitions.',
    iconName: 'Sliders',
    corePattern: 'Opposing / Converging Pointers',
    estimatedHours: '6-8 hrs',
    problems: [
      {
        id: 'lc-1',
        leetcodeNumber: 1,
        title: 'Two Sum',
        slug: 'two-sum',
        leetcodeUrl: 'https://leetcode.com/problems/two-sum/',
        difficulty: 'EASY',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: 'Hash Map Complement',
        companyTags: ['Amazon', 'TCS Prime', 'Infosys SP', 'Adobe', 'Google'],
        keyIntuition: 'Store each visited number in a Hash Map; check if (target - num) exists in O(1) time.',
        order: 1,
      },
      {
        id: 'lc-167',
        leetcodeNumber: 167,
        title: 'Two Sum II - Input Array Is Sorted',
        slug: 'two-sum-ii-input-array-is-sorted',
        leetcodeUrl: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
        difficulty: 'MEDIUM',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: 'Opposing Pointers',
        companyTags: ['Amazon', 'Microsoft', 'Cognizant GenC Next'],
        keyIntuition: 'Since the array is sorted, initialize left at 0 and right at n-1. If sum > target, decrement right; if sum < target, increment left.',
        order: 2,
      },
      {
        id: 'lc-15',
        leetcodeNumber: 15,
        title: '3Sum',
        slug: '3sum',
        leetcodeUrl: 'https://leetcode.com/problems/3sum/',
        difficulty: 'MEDIUM',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: 'Sorted Triplet Search',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Sort the array first. Fix element i, then run Two Pointers on the remaining range while skipping consecutive duplicate values.',
        order: 3,
      },
      {
        id: 'lc-11',
        leetcodeNumber: 11,
        title: 'Container With Most Water',
        slug: 'container-with-most-water',
        leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water/',
        difficulty: 'MEDIUM',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: 'Greedy Two Pointers',
        companyTags: ['Amazon', 'Google', 'Flipkart', 'Goldman Sachs'],
        keyIntuition: 'Area is bounded by min(height[left], height[right]). Always advance the pointer pointing to the shorter vertical line.',
        order: 4,
      },
      {
        id: 'lc-42',
        leetcodeNumber: 42,
        title: 'Trapping Rain Water',
        slug: 'trapping-rain-water',
        leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water/',
        difficulty: 'HARD',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: 'Dual Max Boundary Tracking',
        companyTags: ['Amazon', 'Microsoft', 'Goldman Sachs', 'Infosys SP'],
        keyIntuition: 'Maintain leftMax and rightMax with two pointers. The lower boundary dictates the trapped water volume at that position.',
        order: 5,
      },
      {
        id: 'lc-75',
        leetcodeNumber: 75,
        title: 'Sort Colors (Dutch National Flag)',
        slug: 'sort-colors',
        leetcodeUrl: 'https://leetcode.com/problems/sort-colors/',
        difficulty: 'MEDIUM',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: '3-Way In-Place Partition',
        companyTags: ['TCS Digital', 'Accenture Advanced', 'Wipro Turbo', 'Amazon'],
        keyIntuition: 'Maintain low, mid, and high pointers. Swap mid with low for 0s, mid with high for 2s, and increment mid for 1s.',
        order: 6,
      },
      {
        id: 'lc-283',
        leetcodeNumber: 283,
        title: 'Move Zeroes',
        slug: 'move-zeroes',
        leetcodeUrl: 'https://leetcode.com/problems/move-zeroes/',
        difficulty: 'EASY',
        stageId: 'stage-1-two-pointers',
        stageTitle: 'Stage 1: Arrays & Two Pointers',
        pattern: 'Slow & Fast Pointers',
        companyTags: ['TCS Digital', 'Cognizant', 'Infosys', 'Capgemini'],
        keyIntuition: 'Slow pointer marks placement index for non-zero elements; fast pointer scans the array. Fill remaining positions with zeros.',
        order: 7,
      },
    ],
  },

  // ── STAGE 2: SLIDING WINDOW & SUBARRAYS ─────────────────────────────────────
  {
    id: 'stage-2-sliding-window',
    stageNumber: 2,
    title: 'Stage 2: Sliding Window & Subarrays',
    cluster: 'Pointers & Arrays',
    description: 'Dynamic and fixed-size contiguous window expansion, shrinking conditions, and Kadane’s prefix algorithm.',
    iconName: 'Layers',
    corePattern: 'Window Expansion & Contraction',
    estimatedHours: '7-9 hrs',
    problems: [
      {
        id: 'lc-53',
        leetcodeNumber: 53,
        title: 'Maximum Subarray (Kadane’s Algorithm)',
        slug: 'maximum-subarray',
        leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/',
        difficulty: 'MEDIUM',
        stageId: 'stage-2-sliding-window',
        stageTitle: 'Stage 2: Sliding Window & Subarrays',
        pattern: 'Running Prefix Sum',
        companyTags: ['Amazon', 'TCS Prime', 'Infosys SP', 'Cognizant'],
        keyIntuition: 'At each index, decide whether to append current element to existing sum or start a fresh subarray if current sum drops negative.',
        order: 1,
      },
      {
        id: 'lc-3',
        leetcodeNumber: 3,
        title: 'Longest Substring Without Repeating Characters',
        slug: 'longest-substring-without-repeating-characters',
        leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
        difficulty: 'MEDIUM',
        stageId: 'stage-2-sliding-window',
        stageTitle: 'Stage 2: Sliding Window & Subarrays',
        pattern: 'Dynamic Variable Window',
        companyTags: ['Amazon', 'Microsoft', 'Adobe', 'TCS Prime'],
        keyIntuition: 'Track character last-seen index with a hash map. Jump the left pointer immediately past duplicate characters.',
        order: 2,
      },
      {
        id: 'lc-424',
        leetcodeNumber: 424,
        title: 'Longest Repeating Character Replacement',
        slug: 'longest-repeating-character-replacement',
        leetcodeUrl: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
        difficulty: 'MEDIUM',
        stageId: 'stage-2-sliding-window',
        stageTitle: 'Stage 2: Sliding Window & Subarrays',
        pattern: 'Frequency Sliding Window',
        companyTags: ['Amazon', 'Google', 'Infosys SP'],
        keyIntuition: 'Window is valid as long as (window_length - max_frequency_char) <= k. Shrink left pointer whenever condition fails.',
        order: 3,
      },
      {
        id: 'lc-76',
        leetcodeNumber: 76,
        title: 'Minimum Window Substring',
        slug: 'minimum-window-substring',
        leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/',
        difficulty: 'HARD',
        stageId: 'stage-2-sliding-window',
        stageTitle: 'Stage 2: Sliding Window & Subarrays',
        pattern: 'Matched Characters Window',
        companyTags: ['Amazon', 'Microsoft', 'Google', 'Flipkart'],
        keyIntuition: 'Maintain required character counts. Expand right until all target characters match; then contract left to minimize length.',
        order: 4,
      },
      {
        id: 'lc-560',
        leetcodeNumber: 560,
        title: 'Subarray Sum Equals K',
        slug: 'subarray-sum-equals-k',
        leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k/',
        difficulty: 'MEDIUM',
        stageId: 'stage-2-sliding-window',
        stageTitle: 'Stage 2: Sliding Window & Subarrays',
        pattern: 'Prefix Sum Hash Map',
        companyTags: ['Amazon', 'Facebook', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Prefix sum difference: if (current_prefix_sum - k) was observed previously, a subarray summing to k terminates at current index.',
        order: 5,
      },
      {
        id: 'lc-239',
        leetcodeNumber: 239,
        title: 'Sliding Window Maximum',
        slug: 'sliding-window-maximum',
        leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum/',
        difficulty: 'HARD',
        stageId: 'stage-2-sliding-window',
        stageTitle: 'Stage 2: Sliding Window & Subarrays',
        pattern: 'Monotonic Deque Window',
        companyTags: ['Amazon', 'Google', 'Microsoft'],
        keyIntuition: 'Store indices in a decreasing monotonic deque so the front index always holds the window maximum in O(1).',
        order: 6,
      },
    ],
  },

  // ── STAGE 3: FAST & SLOW POINTERS & LINKED LISTS ────────────────────────────
  {
    id: 'stage-3-fast-slow-pointers',
    stageNumber: 3,
    title: 'Stage 3: Fast & Slow Pointers & Linked Lists',
    cluster: 'Linear Structures',
    description: 'Pointer cycles, Floyd’s cycle finding, list reversal, middle discovery, and k-group transformations.',
    iconName: 'GitMerge',
    corePattern: 'Tortoise & Hare / Pointer Manipulation',
    estimatedHours: '6-8 hrs',
    problems: [
      {
        id: 'lc-206',
        leetcodeNumber: 206,
        title: 'Reverse Linked List',
        slug: 'reverse-linked-list',
        leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/',
        difficulty: 'EASY',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: 'In-Place Pointer Reversal',
        companyTags: ['Amazon', 'TCS Digital', 'Infosys', 'Cognizant', 'Wipro'],
        keyIntuition: 'Iteratively redirect current.next to prev pointer while preserving next node reference using three pointers.',
        order: 1,
      },
      {
        id: 'lc-141',
        leetcodeNumber: 141,
        title: 'Linked List Cycle',
        slug: 'linked-list-cycle',
        leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/',
        difficulty: 'EASY',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: 'Floyd’s Cycle Detection',
        companyTags: ['Amazon', 'Microsoft', 'Accenture', 'Capgemini'],
        keyIntuition: 'Move slow pointer 1 step and fast pointer 2 steps. If there is a loop, fast will inevitably collide with slow.',
        order: 2,
      },
      {
        id: 'lc-142',
        leetcodeNumber: 142,
        title: 'Linked List Cycle II (Find Start of Loop)',
        slug: 'linked-list-cycle-ii',
        leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle-ii/',
        difficulty: 'MEDIUM',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: 'Mathematical Cycle Origin',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime'],
        keyIntuition: 'Upon collision, reset one pointer to head. Moving both 1 step each brings them together at the loop entrance.',
        order: 3,
      },
      {
        id: 'lc-876',
        leetcodeNumber: 876,
        title: 'Middle of the Linked List',
        slug: 'middle-of-the-linked-list',
        leetcodeUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/',
        difficulty: 'EASY',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: '2x Speed Ratio',
        companyTags: ['TCS Digital', 'Infosys', 'Wipro Turbo'],
        keyIntuition: 'When fast pointer reaches list tail (advancing 2 nodes per turn), slow pointer sits precisely at the middle node.',
        order: 4,
      },
      {
        id: 'lc-21',
        leetcodeNumber: 21,
        title: 'Merge Two Sorted Lists',
        slug: 'merge-two-sorted-lists',
        leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/',
        difficulty: 'EASY',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: 'Dummy Head Merging',
        companyTags: ['Amazon', 'TCS Digital', 'Cognizant', 'Microsoft'],
        keyIntuition: 'Attach a dummy head node and iteratively append the smaller node from the two lists.',
        order: 5,
      },
      {
        id: 'lc-143',
        leetcodeNumber: 143,
        title: 'Reorder List',
        slug: 'reorder-list',
        leetcodeUrl: 'https://leetcode.com/problems/reorder-list/',
        difficulty: 'MEDIUM',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: 'Split, Reverse & Interleave',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP'],
        keyIntuition: 'Find middle using fast/slow pointers, reverse the second half, and interleave nodes from first and second halves.',
        order: 6,
      },
      {
        id: 'lc-19',
        leetcodeNumber: 19,
        title: 'Remove Nth Node From End of List',
        slug: 'remove-nth-node-from-end-of-list',
        leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
        difficulty: 'MEDIUM',
        stageId: 'stage-3-fast-slow-pointers',
        stageTitle: 'Stage 3: Fast & Slow Pointers & Linked Lists',
        pattern: 'Offset Pointers',
        companyTags: ['Amazon', 'Adobe', 'TCS Prime'],
        keyIntuition: 'Advance first pointer by N steps ahead. Then move first and second pointers together until first reaches the end.',
        order: 7,
      },
    ],
  },

  // ── STAGE 4: STACKS, QUEUES & MONOTONIC PATTERNS ────────────────────────────
  {
    id: 'stage-4-monotonic-stack',
    stageNumber: 4,
    title: 'Stage 4: Stacks, Queues & Monotonic Patterns',
    cluster: 'Linear Structures',
    description: 'LIFO evaluation, monotonic increasing/decreasing stacks, and nearest boundary computations.',
    iconName: 'Layers',
    corePattern: 'Monotonic Stack / LIFO',
    estimatedHours: '6-8 hrs',
    problems: [
      {
        id: 'lc-20',
        leetcodeNumber: 20,
        title: 'Valid Parentheses',
        slug: 'valid-parentheses',
        leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses/',
        difficulty: 'EASY',
        stageId: 'stage-4-monotonic-stack',
        stageTitle: 'Stage 4: Stacks, Queues & Monotonic Patterns',
        pattern: 'Stack Bracket Matching',
        companyTags: ['Amazon', 'TCS Digital', 'Infosys', 'Cognizant', 'Microsoft'],
        keyIntuition: 'Push opening brackets to stack; pop and verify match whenever a closing bracket appears. Stack must be empty at the end.',
        order: 1,
      },
      {
        id: 'lc-155',
        leetcodeNumber: 155,
        title: 'Min Stack',
        slug: 'min-stack',
        leetcodeUrl: 'https://leetcode.com/problems/min-stack/',
        difficulty: 'MEDIUM',
        stageId: 'stage-4-monotonic-stack',
        stageTitle: 'Stage 4: Stacks, Queues & Monotonic Patterns',
        pattern: 'Auxiliary Min Tracking',
        companyTags: ['Amazon', 'Goldman Sachs', 'TCS Prime'],
        keyIntuition: 'Maintain an auxiliary stack paired with each element to store the minimum value up to that stack depth in O(1).',
        order: 2,
      },
      {
        id: 'lc-739',
        leetcodeNumber: 739,
        title: 'Daily Temperatures',
        slug: 'daily-temperatures',
        leetcodeUrl: 'https://leetcode.com/problems/daily-temperatures/',
        difficulty: 'MEDIUM',
        stageId: 'stage-4-monotonic-stack',
        stageTitle: 'Stage 4: Stacks, Queues & Monotonic Patterns',
        pattern: 'Monotonic Decreasing Stack',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP'],
        keyIntuition: 'Maintain a stack of indices with decreasing temperatures. When a warmer day is found, pop and calculate index difference.',
        order: 3,
      },
      {
        id: 'lc-496',
        leetcodeNumber: 496,
        title: 'Next Greater Element I',
        slug: 'next-greater-element-i',
        leetcodeUrl: 'https://leetcode.com/problems/next-greater-element-i/',
        difficulty: 'EASY',
        stageId: 'stage-4-monotonic-stack',
        stageTitle: 'Stage 4: Stacks, Queues & Monotonic Patterns',
        pattern: 'Next Greater Lookup',
        companyTags: ['Amazon', 'TCS Digital', 'Wipro Turbo'],
        keyIntuition: 'Iterate backwards or forwards with a monotonic stack, storing next greater numbers in a hash map for fast query lookup.',
        order: 4,
      },
      {
        id: 'lc-84',
        leetcodeNumber: 84,
        title: 'Largest Rectangle in Histogram',
        slug: 'largest-rectangle-in-histogram',
        leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
        difficulty: 'HARD',
        stageId: 'stage-4-monotonic-stack',
        stageTitle: 'Stage 4: Stacks, Queues & Monotonic Patterns',
        pattern: 'Boundary Monotonic Stack',
        companyTags: ['Amazon', 'Google', 'Microsoft'],
        keyIntuition: 'Compute previous smaller and next smaller bars using a monotonic increasing stack to establish the maximum width for each height.',
        order: 5,
      },
      {
        id: 'lc-150',
        leetcodeNumber: 150,
        title: 'Evaluate Reverse Polish Notation',
        slug: 'evaluate-reverse-polish-notation',
        leetcodeUrl: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
        difficulty: 'MEDIUM',
        stageId: 'stage-4-monotonic-stack',
        stageTitle: 'Stage 4: Stacks, Queues & Monotonic Patterns',
        pattern: 'Postfix Stack Evaluation',
        companyTags: ['Amazon', 'LinkedIn', 'TCS Prime'],
        keyIntuition: 'Push numeric operands onto stack; on encountering an operator, pop two operands, apply the operation, and push result back.',
        order: 6,
      },
    ],
  },

  // ── STAGE 5: BINARY SEARCH & INTERVALS ──────────────────────────────────────
  {
    id: 'stage-5-binary-search',
    stageNumber: 5,
    title: 'Stage 5: Binary Search & Intervals',
    cluster: 'Searching & Intervals',
    description: 'Logarithmic search space elimination, rotated arrays, peak element detection, and interval scheduling.',
    iconName: 'Search',
    corePattern: 'O(log N) Space Reduction / Interval Sorting',
    estimatedHours: '7-9 hrs',
    problems: [
      {
        id: 'lc-704',
        leetcodeNumber: 704,
        title: 'Binary Search',
        slug: 'binary-search',
        leetcodeUrl: 'https://leetcode.com/problems/binary-search/',
        difficulty: 'EASY',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Classic Binary Search',
        companyTags: ['Amazon', 'TCS Digital', 'Infosys', 'Capgemini'],
        keyIntuition: 'Calculate mid with `low + (high - low) / 2` to avoid 32-bit integer overflow. Halve the search space based on comparisons.',
        order: 1,
      },
      {
        id: 'lc-33',
        leetcodeNumber: 33,
        title: 'Search in Rotated Sorted Array',
        slug: 'search-in-rotated-sorted-array',
        leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
        difficulty: 'MEDIUM',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Sorted Half Identification',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'At least one half of a rotated array is always strictly sorted. Check if target lies within the sorted half to discard the other half.',
        order: 2,
      },
      {
        id: 'lc-153',
        leetcodeNumber: 153,
        title: 'Find Minimum in Rotated Sorted Array',
        slug: 'find-minimum-in-rotated-sorted-array',
        leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
        difficulty: 'MEDIUM',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Inflection Point Search',
        companyTags: ['Amazon', 'Microsoft', 'Goldman Sachs'],
        keyIntuition: 'Compare mid with right. If nums[mid] > nums[right], the minimum lies in the right half; otherwise, it is in the left half.',
        order: 3,
      },
      {
        id: 'lc-852',
        leetcodeNumber: 852,
        title: 'Peak Index in a Mountain Array',
        slug: 'peak-index-in-a-mountain-array',
        leetcodeUrl: 'https://leetcode.com/problems/peak-index-in-a-mountain-array/',
        difficulty: 'MEDIUM',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Slope Comparison',
        companyTags: ['Amazon', 'Google', 'Cognizant GenC Next'],
        keyIntuition: 'If nums[mid] < nums[mid + 1], you are climbing the upward slope, so the peak lies right; otherwise it lies left.',
        order: 4,
      },
      {
        id: 'lc-56',
        leetcodeNumber: 56,
        title: 'Merge Intervals',
        slug: 'merge-intervals',
        leetcodeUrl: 'https://leetcode.com/problems/merge-intervals/',
        difficulty: 'MEDIUM',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Start Time Sort & Merge',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Sort intervals by start time. If current interval starts before previous ends, merge by updating the previous end to max(end1, end2).',
        order: 5,
      },
      {
        id: 'lc-57',
        leetcodeNumber: 57,
        title: 'Insert Interval',
        slug: 'insert-interval',
        leetcodeUrl: 'https://leetcode.com/problems/insert-interval/',
        difficulty: 'MEDIUM',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Three-Phase Interval Scan',
        companyTags: ['Amazon', 'Google', 'LinkedIn'],
        keyIntuition: 'Add non-overlapping intervals before newInterval, merge all overlapping intervals into newInterval, then append remaining intervals.',
        order: 6,
      },
      {
        id: 'lc-435',
        leetcodeNumber: 435,
        title: 'Non-overlapping Intervals',
        slug: 'non-overlapping-intervals',
        leetcodeUrl: 'https://leetcode.com/problems/non-overlapping-intervals/',
        difficulty: 'MEDIUM',
        stageId: 'stage-5-binary-search',
        stageTitle: 'Stage 5: Binary Search & Intervals',
        pattern: 'Greedy Earliest End Time',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP'],
        keyIntuition: 'Sort intervals by end time. Always retain the interval that finishes earliest to leave maximum room for subsequent intervals.',
        order: 7,
      },
    ],
  },

  // ── STAGE 6: BINARY TREES & BSTS (BFS & DFS) ────────────────────────────────
  {
    id: 'stage-6-binary-trees',
    stageNumber: 6,
    title: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
    cluster: 'Hierarchical Structures',
    description: 'Tree recursions, depth-first traversals, queue-based level order scanning, and binary search tree properties.',
    iconName: 'Brain',
    corePattern: 'Recursion / Queue-based BFS',
    estimatedHours: '8-10 hrs',
    problems: [
      {
        id: 'lc-104',
        leetcodeNumber: 104,
        title: 'Maximum Depth of Binary Tree',
        slug: 'maximum-depth-of-binary-tree',
        leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
        difficulty: 'EASY',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'Post-order DFS Height',
        companyTags: ['Amazon', 'TCS Digital', 'Infosys', 'Wipro'],
        keyIntuition: 'Depth is `1 + max(maxDepth(left), maxDepth(right))`. Base case returns 0 for null nodes.',
        order: 1,
      },
      {
        id: 'lc-226',
        leetcodeNumber: 226,
        title: 'Invert Binary Tree',
        slug: 'invert-binary-tree',
        leetcodeUrl: 'https://leetcode.com/problems/invert-binary-tree/',
        difficulty: 'EASY',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'Subtree Swap Recursion',
        companyTags: ['Amazon', 'Google', 'TCS Digital'],
        keyIntuition: 'Swap root.left and root.right recursively for every node in the binary tree.',
        order: 2,
      },
      {
        id: 'lc-543',
        leetcodeNumber: 543,
        title: 'Diameter of Binary Tree',
        slug: 'diameter-of-binary-tree',
        leetcodeUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/',
        difficulty: 'EASY',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'Global Max Path Calculation',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime'],
        keyIntuition: 'At each node, the longest path passing through it is `left_height + right_height`. Update a global diameter counter while returning height.',
        order: 3,
      },
      {
        id: 'lc-102',
        leetcodeNumber: 102,
        title: 'Binary Tree Level Order Traversal',
        slug: 'binary-tree-level-order-traversal',
        leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
        difficulty: 'MEDIUM',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'Queue-Based BFS',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP', 'Cognizant'],
        keyIntuition: 'Use a FIFO Queue. For each level, capture `queue.size()` to process only nodes belonging to that specific level before pushing children.',
        order: 4,
      },
      {
        id: 'lc-235',
        leetcodeNumber: 235,
        title: 'Lowest Common Ancestor of a BST',
        slug: 'lowest-common-ancestor-of-a-binary-search-tree',
        leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
        difficulty: 'MEDIUM',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'BST Split Point',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime'],
        keyIntuition: 'If both p and q values are greater than root, move right; if both are smaller, move left; otherwise, root is the LCA split point.',
        order: 5,
      },
      {
        id: 'lc-236',
        leetcodeNumber: 236,
        title: 'Lowest Common Ancestor of a Binary Tree',
        slug: 'lowest-common-ancestor-of-a-binary-tree',
        leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
        difficulty: 'MEDIUM',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'Post-Order Search Propagation',
        companyTags: ['Amazon', 'Facebook', 'Microsoft', 'Infosys SP'],
        keyIntuition: 'Search left and right subtrees. If both return non-null, root is the LCA; if only one returns non-null, pass that node upward.',
        order: 6,
      },
      {
        id: 'lc-98',
        leetcodeNumber: 98,
        title: 'Validate Binary Search Tree',
        slug: 'validate-binary-search-tree',
        leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/',
        difficulty: 'MEDIUM',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'Range Boundary Validation',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime'],
        keyIntuition: 'Pass allowable (min, max) bounds recursively down the tree. Every node value must strictly satisfy `min < val < max`.',
        order: 7,
      },
      {
        id: 'lc-230',
        leetcodeNumber: 230,
        title: 'Kth Smallest Element in a BST',
        slug: 'kth-smallest-element-in-a-bst',
        leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
        difficulty: 'MEDIUM',
        stageId: 'stage-6-binary-trees',
        stageTitle: 'Stage 6: Binary Trees & BSTs (BFS & DFS)',
        pattern: 'In-Order Monotonic Traversal',
        companyTags: ['Amazon', 'Uber', 'Infosys SP'],
        keyIntuition: 'In-order traversal of a BST visits elements in strictly ascending sorted order. Decrement k at each visited node until k reaches 0.',
        order: 8,
      },
    ],
  },

  // ── STAGE 7: HEAPS & PRIORITY QUEUES (TOP 'K' ELEMENTS) ─────────────────────
  {
    id: 'stage-7-heaps-top-k',
    stageNumber: 7,
    title: 'Stage 7: Heaps & Priority Queues (Top \'K\')',
    cluster: 'Hierarchical Structures',
    description: 'Min-heaps and Max-heaps for top-K elements, streaming medians, and efficient K-way merges.',
    iconName: 'Sparkles',
    corePattern: 'PriorityQueue / Partial Ordering',
    estimatedHours: '6-7 hrs',
    problems: [
      {
        id: 'lc-215',
        leetcodeNumber: 215,
        title: 'Kth Largest Element in an Array',
        slug: 'kth-largest-element-in-an-array',
        leetcodeUrl: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
        difficulty: 'MEDIUM',
        stageId: 'stage-7-heaps-top-k',
        stageTitle: 'Stage 7: Heaps & Priority Queues (Top \'K\')',
        pattern: 'Min-Heap Size K',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Maintain a Min-Heap capped at size K. When size exceeds K, evict minimum. The top element is the Kth largest in O(N log K).',
        order: 1,
      },
      {
        id: 'lc-347',
        leetcodeNumber: 347,
        title: 'Top K Frequent Elements',
        slug: 'top-k-frequent-elements',
        leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/',
        difficulty: 'MEDIUM',
        stageId: 'stage-7-heaps-top-k',
        stageTitle: 'Stage 7: Heaps & Priority Queues (Top \'K\')',
        pattern: 'Bucket Sort / Min-Heap',
        companyTags: ['Amazon', 'Facebook', 'Infosys SP'],
        keyIntuition: 'Count frequencies with a map, then use a Min-Heap of size K based on frequency, or Bucket Sort indexed by frequency in O(N).',
        order: 2,
      },
      {
        id: 'lc-295',
        leetcodeNumber: 295,
        title: 'Find Median from Data Stream',
        slug: 'find-median-from-data-stream',
        leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/',
        difficulty: 'HARD',
        stageId: 'stage-7-heaps-top-k',
        stageTitle: 'Stage 7: Heaps & Priority Queues (Top \'K\')',
        pattern: 'Dual Balanced Heaps',
        companyTags: ['Amazon', 'Google', 'Goldman Sachs'],
        keyIntuition: 'Maintain small numbers in Max-Heap and large numbers in Min-Heap. Balance sizes so difference <= 1 to fetch median in O(1).',
        order: 3,
      },
      {
        id: 'lc-23',
        leetcodeNumber: 23,
        title: 'Merge k Sorted Lists',
        slug: 'merge-k-sorted-lists',
        leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists/',
        difficulty: 'HARD',
        stageId: 'stage-7-heaps-top-k',
        stageTitle: 'Stage 7: Heaps & Priority Queues (Top \'K\')',
        pattern: 'K-Way Min-Heap Merge',
        companyTags: ['Amazon', 'Microsoft', 'Google'],
        keyIntuition: 'Insert head of each list into a Min-Heap. Pop smallest node, append to result, and insert its next node into the heap in O(N log K).',
        order: 4,
      },
      {
        id: 'lc-621',
        leetcodeNumber: 621,
        title: 'Task Scheduler',
        slug: 'task-scheduler',
        leetcodeUrl: 'https://leetcode.com/problems/task-scheduler/',
        difficulty: 'MEDIUM',
        stageId: 'stage-7-heaps-top-k',
        stageTitle: 'Stage 7: Heaps & Priority Queues (Top \'K\')',
        pattern: 'Greedy Frequency Slotting',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP'],
        keyIntuition: 'The highest frequency tasks dictate the minimum number of idle slots required: `(max_freq - 1) * (n + 1) + count(max_freq_tasks)`.',
        order: 5,
      },
    ],
  },

  // ── STAGE 8: RECURSION & BACKTRACKING ───────────────────────────────────────
  {
    id: 'stage-8-backtracking',
    stageNumber: 8,
    title: 'Stage 8: Recursion & Backtracking',
    cluster: 'Advanced Algorithms',
    description: 'Decision trees, state exploration, choice rollback, subset generation, and search pruning.',
    iconName: 'Code2',
    corePattern: 'Choose -> Explore -> Unchoose',
    estimatedHours: '7-9 hrs',
    problems: [
      {
        id: 'lc-78',
        leetcodeNumber: 78,
        title: 'Subsets (Power Set)',
        slug: 'subsets',
        leetcodeUrl: 'https://leetcode.com/problems/subsets/',
        difficulty: 'MEDIUM',
        stageId: 'stage-8-backtracking',
        stageTitle: 'Stage 8: Recursion & Backtracking',
        pattern: 'Include / Exclude Recursion',
        companyTags: ['Amazon', 'TCS Prime', 'Infosys SP', 'Cognizant'],
        keyIntuition: 'At each index, branch into two decisions: include current element or exclude it. Add current state to result at each tree step.',
        order: 1,
      },
      {
        id: 'lc-39',
        leetcodeNumber: 39,
        title: 'Combination Sum',
        slug: 'combination-sum',
        leetcodeUrl: 'https://leetcode.com/problems/combination-sum/',
        difficulty: 'MEDIUM',
        stageId: 'stage-8-backtracking',
        stageTitle: 'Stage 8: Recursion & Backtracking',
        pattern: 'Unbounded Choice Backtracking',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Since elements can be chosen repeatedly, pass the same index forward when including; advance index when excluding.',
        order: 2,
      },
      {
        id: 'lc-46',
        leetcodeNumber: 46,
        title: 'Permutations',
        slug: 'permutations',
        leetcodeUrl: 'https://leetcode.com/problems/permutations/',
        difficulty: 'MEDIUM',
        stageId: 'stage-8-backtracking',
        stageTitle: 'Stage 8: Recursion & Backtracking',
        pattern: 'State In-Place Swap',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP', 'Adobe'],
        keyIntuition: 'Swap elements in-place to explore all arrangement permutations, then backtrack by swapping them back.',
        order: 3,
      },
      {
        id: 'lc-79',
        leetcodeNumber: 79,
        title: 'Word Search in Grid',
        slug: 'word-search',
        leetcodeUrl: 'https://leetcode.com/problems/word-search/',
        difficulty: 'MEDIUM',
        stageId: 'stage-8-backtracking',
        stageTitle: 'Stage 8: Recursion & Backtracking',
        pattern: '2D Grid DFS Backtracking',
        companyTags: ['Amazon', 'Microsoft', 'Goldman Sachs'],
        keyIntuition: 'Explore 4 directions recursively matching character index. Mark visited cell in-place (e.g. with \'#\') and restore on backtrack.',
        order: 4,
      },
      {
        id: 'lc-131',
        leetcodeNumber: 131,
        title: 'Palindrome Partitioning',
        slug: 'palindrome-partitioning',
        leetcodeUrl: 'https://leetcode.com/problems/palindrome-partitioning/',
        difficulty: 'MEDIUM',
        stageId: 'stage-8-backtracking',
        stageTitle: 'Stage 8: Recursion & Backtracking',
        pattern: 'Substring Palindrome Branching',
        companyTags: ['Amazon', 'Google', 'Infosys SP'],
        keyIntuition: 'Partition string prefix if it forms a valid palindrome, then recursively partition the remainder of the string.',
        order: 5,
      },
      {
        id: 'lc-51',
        leetcodeNumber: 51,
        title: 'N-Queens',
        slug: 'n-queens',
        leetcodeUrl: 'https://leetcode.com/problems/n-queens/',
        difficulty: 'HARD',
        stageId: 'stage-8-backtracking',
        stageTitle: 'Stage 8: Recursion & Backtracking',
        pattern: 'Row-by-Row Constraint Check',
        companyTags: ['Amazon', 'Google', 'Infosys SP'],
        keyIntuition: 'Place queen row by row. Track attacked columns, positive diagonals (r + c), and negative diagonals (r - c) in boolean sets in O(1).',
        order: 6,
      },
    ],
  },

  // ── STAGE 9: DYNAMIC PROGRAMMING (PLACEMENT CLASSICS) ───────────────────────
  {
    id: 'stage-9-dynamic-programming',
    stageNumber: 9,
    title: 'Stage 9: Dynamic Programming Classics',
    cluster: 'Advanced Algorithms',
    description: 'Overlapping subproblems, optimal substructure, 0/1 Knapsack, Longest Common Subsequence, and 1D/2D state transitions.',
    iconName: 'Terminal',
    corePattern: 'Memoization / Tabulation',
    estimatedHours: '9-12 hrs',
    problems: [
      {
        id: 'lc-70',
        leetcodeNumber: 70,
        title: 'Climbing Stairs',
        slug: 'climbing-stairs',
        leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs/',
        difficulty: 'EASY',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: 'Fibonacci State Transition',
        companyTags: ['TCS Digital', 'Infosys', 'Cognizant', 'Amazon'],
        keyIntuition: 'Way to reach step N is `dp[n] = dp[n-1] + dp[n-2]`. Space can be optimized to O(1) using two rolling variables.',
        order: 1,
      },
      {
        id: 'lc-198',
        leetcodeNumber: 198,
        title: 'House Robber',
        slug: 'house-robber',
        leetcodeUrl: 'https://leetcode.com/problems/house-robber/',
        difficulty: 'MEDIUM',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: 'Non-Adjacent Max Decision',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'At each house, `max(rob_current + dp[i-2], skip_current + dp[i-1])`. Two variables suffice for O(1) space.',
        order: 2,
      },
      {
        id: 'lc-322',
        leetcodeNumber: 322,
        title: 'Coin Change',
        slug: 'coin-change',
        leetcodeUrl: 'https://leetcode.com/problems/coin-change/',
        difficulty: 'MEDIUM',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: 'Unbounded Knapsack Min Count',
        companyTags: ['Amazon', 'Goldman Sachs', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'For each sub-amount from 1 to target, try every coin: `dp[a] = min(dp[a], 1 + dp[a - coin])`.',
        order: 3,
      },
      {
        id: 'lc-300',
        leetcodeNumber: 300,
        title: 'Longest Increasing Subsequence (LIS)',
        slug: 'longest-increasing-subsequence',
        leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/',
        difficulty: 'MEDIUM',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: 'O(N log N) Patience Sort',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP'],
        keyIntuition: 'Maintain tails array of smallest tail of all increasing subsequences of length i; use binary search to replace or append.',
        order: 4,
      },
      {
        id: 'lc-416',
        leetcodeNumber: 416,
        title: 'Partition Equal Subset Sum',
        slug: 'partition-equal-subset-sum',
        leetcodeUrl: 'https://leetcode.com/problems/partition-equal-subset-sum/',
        difficulty: 'MEDIUM',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: '0/1 Knapsack Target Sum',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime'],
        keyIntuition: 'Target is sum(nums) / 2. Run 1D boolean 0/1 knapsack backwards from target to num to avoid reusing the same element.',
        order: 5,
      },
      {
        id: 'lc-1143',
        leetcodeNumber: 1143,
        title: 'Longest Common Subsequence (LCS)',
        slug: 'longest-common-subsequence',
        leetcodeUrl: 'https://leetcode.com/problems/longest-common-subsequence/',
        difficulty: 'MEDIUM',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: '2D Grid String Matching',
        companyTags: ['Amazon', 'Microsoft', 'Infosys SP', 'Cognizant'],
        keyIntuition: 'If chars match, `1 + dp[i-1][j-1]`; else `max(dp[i-1][j], dp[i][j-1])`. Can be space-optimized to two rows.',
        order: 6,
      },
      {
        id: 'lc-72',
        leetcodeNumber: 72,
        title: 'Edit Distance',
        slug: 'edit-distance',
        leetcodeUrl: 'https://leetcode.com/problems/edit-distance/',
        difficulty: 'HARD',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: '3-Way Operation Transition',
        companyTags: ['Amazon', 'Google', 'Microsoft'],
        keyIntuition: 'If chars match, no cost; else `1 + min(insert: dp[i][j-1], delete: dp[i-1][j], replace: dp[i-1][j-1])`.',
        order: 7,
      },
      {
        id: 'lc-139',
        leetcodeNumber: 139,
        title: 'Word Break',
        slug: 'word-break',
        leetcodeUrl: 'https://leetcode.com/problems/word-break/',
        difficulty: 'MEDIUM',
        stageId: 'stage-9-dynamic-programming',
        stageTitle: 'Stage 9: Dynamic Programming Classics',
        pattern: '1D Prefix Decomposition',
        companyTags: ['Amazon', 'Facebook', 'Infosys SP'],
        keyIntuition: '`dp[i] = true` if there exists `j < i` such that `dp[j] == true` and substring `s[j..i]` is in the word dictionary.',
        order: 8,
      },
    ],
  },

  // ── STAGE 10: GRAPHS & TOPOLOGICAL SORT ─────────────────────────────────────
  {
    id: 'stage-10-graphs',
    stageNumber: 10,
    title: 'Stage 10: Graphs & Topological Sort',
    cluster: 'Advanced Algorithms',
    description: 'Connected components, multi-source BFS, cycle detection in directed graphs, and Kahn’s dependency resolution.',
    iconName: 'Network',
    corePattern: 'Graph BFS / DFS / Kahn\'s Algorithm',
    estimatedHours: '8-10 hrs',
    problems: [
      {
        id: 'lc-200',
        leetcodeNumber: 200,
        title: 'Number of Islands',
        slug: 'number-of-islands',
        leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'Flood Fill DFS',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP', 'Google'],
        keyIntuition: 'On finding \'1\', increment island counter and flood-fill sink all 4 adjacent connected land cells to \'0\' recursively.',
        order: 1,
      },
      {
        id: 'lc-133',
        leetcodeNumber: 133,
        title: 'Clone Graph',
        slug: 'clone-graph',
        leetcodeUrl: 'https://leetcode.com/problems/clone-graph/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'DFS Clone Hash Map',
        companyTags: ['Amazon', 'Facebook', 'Infosys SP'],
        keyIntuition: 'Maintain a map of `original_node -> cloned_node`. Recursively clone neighbors to handle cyclic connections without infinite loops.',
        order: 2,
      },
      {
        id: 'lc-994',
        leetcodeNumber: 994,
        title: 'Rotting Oranges',
        slug: 'rotting-oranges',
        leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'Multi-Source Level BFS',
        companyTags: ['Amazon', 'Microsoft', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Enqueue all initially rotten oranges simultaneously. Run step-by-step level BFS to rot adjacent fresh oranges until none remain.',
        order: 3,
      },
      {
        id: 'lc-207',
        leetcodeNumber: 207,
        title: 'Course Schedule (Cycle Detection)',
        slug: 'course-schedule',
        leetcodeUrl: 'https://leetcode.com/problems/course-schedule/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'Kahn’s Indegree Topological BFS',
        companyTags: ['Amazon', 'Google', 'TCS Prime', 'Infosys SP'],
        keyIntuition: 'Build adjacency list and in-degree array. Push courses with 0 in-degree to queue. If processed courses count < numCourses, a cycle exists.',
        order: 4,
      },
      {
        id: 'lc-210',
        leetcodeNumber: 210,
        title: 'Course Schedule II (Order of Completion)',
        slug: 'course-schedule-ii',
        leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'Topological Order Output',
        companyTags: ['Amazon', 'Microsoft', 'Uber'],
        keyIntuition: 'Same as Course Schedule I, but record the order of nodes popped from the 0-indegree queue into the result array.',
        order: 5,
      },
      {
        id: 'lc-417',
        leetcodeNumber: 417,
        title: 'Pacific Atlantic Water Flow',
        slug: 'pacific-atlantic-water-flow',
        leetcodeUrl: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'Reverse Boundary DFS',
        companyTags: ['Amazon', 'Google', 'Infosys SP'],
        keyIntuition: 'Work backwards: start DFS from ocean borders upward into higher cells. Intersect cells reachable by both Pacific and Atlantic oceans.',
        order: 6,
      },
      {
        id: 'lc-743',
        leetcodeNumber: 743,
        title: 'Network Delay Time',
        slug: 'network-delay-time',
        leetcodeUrl: 'https://leetcode.com/problems/network-delay-time/',
        difficulty: 'MEDIUM',
        stageId: 'stage-10-graphs',
        stageTitle: 'Stage 10: Graphs & Topological Sort',
        pattern: 'Dijkstra’s Shortest Path',
        companyTags: ['Amazon', 'Google', 'Microsoft'],
        keyIntuition: 'Use a Min-Heap PriorityQueue tracking `(travel_time, node)`. Return maximum shortest path to any node or -1 if unreachable.',
        order: 7,
      },
    ],
  },
];

// Helper: All problems flattened
export const ALL_CAMPUS_DSA_PROBLEMS: CampusDsaProblem[] = CAMPUS_DSA_ROADMAP_STAGES.flatMap(
  stage => stage.problems
);
