import type { ProgrammingTopic, ProgrammingProblem } from '@/types/technical';

export const PROGRAMMING_TOPICS: ProgrammingTopic[] = [
  // ── STAGE 1: LANGUAGE & CONTROL FLOW FOUNDATIONS ──
  {
    id: 'syntax-operators',
    title: 'Syntax, Operators & Typecasting',
    cluster: 'Stage 1: Language & Control Flow',
    description: 'Data types, fast I/O, arithmetic & bitwise operator precedence, typecasting, and ASCII arithmetic.',
    iconName: 'Code2',
    category: 'SYNTAX_BASICS',
    order: 1,
  },
  {
    id: 'conditionals-loops',
    title: 'Conditionals & Iteration Loops',
    cluster: 'Stage 1: Language & Control Flow',
    description: 'If-else branches, switch-case calculators, while/for loops, break/continue, and summation logic.',
    iconName: 'Terminal',
    category: 'SYNTAX_BASICS',
    order: 2,
  },

  // ── STAGE 2: MATHEMATICAL & NUMBER LOGIC ──
  {
    id: 'digit-manipulation',
    title: 'Digit Extraction & Manipulation',
    cluster: 'Stage 2: Mathematical & Number Logic',
    description: 'Modulo 10 extractions, counting digits, reversing integers, digital roots, and palindrome numbers.',
    iconName: 'Hash',
    category: 'NUMBER_LOGIC',
    order: 3,
  },
  {
    id: 'primes-divisibility',
    title: 'Primes, Divisibility & Euclidean Math',
    cluster: 'Stage 2: Mathematical & Number Logic',
    description: 'Prime checks in O(sqrt(N)), Sieve of Eratosthenes, Euclidean GCD/LCM, and divisor extraction.',
    iconName: 'Binary',
    category: 'NUMBER_LOGIC',
    order: 4,
  },
  {
    id: 'special-numbers',
    title: 'Special Numbers & Sequences',
    cluster: 'Stage 2: Mathematical & Number Logic',
    description: 'Armstrong, Strong, Harshad, Perfect, Automorphic numbers, and the Fibonacci sequence.',
    iconName: 'Sparkles',
    category: 'NUMBER_LOGIC',
    order: 5,
  },

  // ── STAGE 3: 2D GRID & PATTERN PROGRAMMING ──
  {
    id: 'patterns',
    title: 'Star, Number & Symmetric Patterns',
    cluster: 'Stage 3: 2D Grid & Patterns',
    description: 'Pyramids, inverted pyramids, hollow shapes, Floyd\'s triangle, Pascal\'s triangle, and butterfly patterns.',
    iconName: 'Shuffle',
    category: 'PATTERNS',
    order: 6,
  },

  // ── STAGE 4: LINEAR DATA STRUCTURES: 1D ARRAYS ──
  {
    id: 'arrays-fundamentals',
    title: '1D Arrays: Fundamentals & Linear Scans',
    cluster: 'Stage 4: 1D Arrays',
    description: 'Min/Max search, in-place reversal, sorted verification, frequency tables, and linear scanning.',
    iconName: 'Layers',
    category: 'ARRAYS',
    order: 7,
  },
  {
    id: 'arrays-two-pointers',
    title: '1D Arrays: Two Pointers & Transformations',
    cluster: 'Stage 4: 1D Arrays',
    description: 'Second largest distinct element, in-place duplicate removal, moving zeroes, and array rotation by K.',
    iconName: 'Sliders',
    category: 'ARRAYS',
    order: 8,
  },
  {
    id: 'arrays-subarrays',
    title: '1D Arrays: Subarrays & Classic Patterns',
    cluster: 'Stage 4: 1D Arrays',
    description: 'Kadane\'s algorithm for maximum subarray sum, missing numbers, leader elements, and running prefix sums.',
    iconName: 'Layers',
    category: 'ARRAYS',
    order: 9,
  },
  {
    id: 'hashing-frequency',
    title: '1D Arrays: Hashing & Frequency Maps',
    cluster: 'Stage 4: 1D Arrays',
    description: 'Direct-index frequency arrays, HashMap lookups, Two Sum in O(N), first non-repeating element, and prefix map lookups.',
    iconName: 'Database',
    category: 'ARRAYS',
    order: 10,
    track: 'PROGRAMMING_150',
  },

  // ── STAGE 5: MATRICES & STRING MANIPULATION ──
  {
    id: 'matrices-grid',
    title: '2D Arrays & Matrix Mathematics',
    cluster: 'Stage 5: Matrices & Strings',
    description: 'Matrix multiplication, in-place transpose, 90° clockwise rotation, and spiral boundary traversal.',
    iconName: 'Grid',
    category: 'ARRAYS',
    order: 11,
  },
  {
    id: 'strings-fundamentals',
    title: 'Strings: Fundamentals & ASCII Logic',
    cluster: 'Stage 5: Matrices & Strings',
    description: 'String length without library calls, vowel/consonant counts, word reversal, and case toggling.',
    iconName: 'Type',
    category: 'STRINGS',
    order: 12,
  },
  {
    id: 'strings-algorithms',
    title: 'Strings: Anagrams, Substrings & Compression',
    cluster: 'Stage 5: Matrices & Strings',
    description: 'Valid Anagram verification, Run-Length Encoding (RLE), longest common prefix, and first non-repeating char.',
    iconName: 'Sparkles',
    category: 'STRINGS',
    order: 13,
  },

  // ── STAGE 6: RECURSION, SEARCHING & BIT HACKS ──
  {
    id: 'recursion-backtracking',
    title: 'Recursion & Backtracking Basics',
    cluster: 'Stage 6: Recursion, Search & Bits',
    description: '1 to N recursion, Tower of Hanoi puzzle, recursive array sum, and Power Set generation.',
    iconName: 'Cpu',
    category: 'RECURSION',
    order: 14,
  },
  {
    id: 'searching-sorting',
    title: 'Searching & Sorting Algorithms',
    cluster: 'Stage 6: Recursion, Search & Bits',
    description: 'Binary search with overflow guards, rotated sorted search, bubble sort, selection sort, and merge sort.',
    iconName: 'Search',
    category: 'SEARCHING_SORTING',
    order: 15,
  },
  {
    id: 'bit-manipulation',
    title: 'Bit Manipulation Hacks & Math Tricks',
    cluster: 'Stage 6: Recursion, Search & Bits',
    description: 'Even/odd check, powers of two, Brian Kernighan\'s bit counter, XOR cancellations, and in-place swaps.',
    iconName: 'Binary',
    category: 'BIT_MANIPULATION',
    order: 16,
    track: 'PROGRAMMING_150',
  },
];

// ============================================================================
// CAMPUS DSA CORE: 15 CURATED PLACEMENT PATTERNS (4 PATTERN CATEGORIES)
// ============================================================================
export const CAMPUS_DSA_TOPICS: ProgrammingTopic[] = [
  // ── POINTERS & SLIDING WINDOW ──
  {
    id: 'dsa-sliding-window',
    title: 'Sliding Window Pattern',
    cluster: 'Pointers & Sliding Window',
    description: 'Subarrays, longest substrings, minimum window substrings, and fixed/dynamic window scans.',
    iconName: 'Sliders',
    category: 'SLIDING_WINDOW',
    order: 1,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-two-pointers',
    title: 'Two Pointers & Trapping Water',
    cluster: 'Pointers & Sliding Window',
    description: 'Opposing pointers, sorted pair sums, container with most water, and Dutch National Flag 3-way partition.',
    iconName: 'Shuffle',
    category: 'TWO_POINTERS',
    order: 2,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-fast-slow-pointers',
    title: 'Fast & Slow Pointers (Tortoise & Hare)',
    cluster: 'Pointers & Sliding Window',
    description: 'Floyd\'s cycle detection in linked lists, middle of linked list, and cycle start detection.',
    iconName: 'Zap',
    category: 'LINKED_LISTS',
    order: 3,
    track: 'CAMPUS_DSA',
  },

  // ── INTERVALS & SORTING ──
  {
    id: 'dsa-monotonic-stack',
    title: 'Monotonic Stack & Queue',
    cluster: 'Intervals & Sorting',
    description: 'Next Greater Element, Daily Temperatures, Largest Rectangle in Histogram, and sliding window maximum.',
    iconName: 'Layers',
    category: 'STACKS_QUEUES',
    order: 4,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-merge-intervals',
    title: 'Merge Intervals & Overlap Logic',
    cluster: 'Intervals & Sorting',
    description: 'Meeting rooms, overlapping interval merging, insert interval, and non-overlapping interval counts.',
    iconName: 'Grid',
    category: 'ARRAYS',
    order: 5,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-cyclic-sort',
    title: 'Cyclic Sort & Missing Range',
    cluster: 'Intervals & Sorting',
    description: 'Find missing numbers, first missing positive, and duplicate element discovery in O(N) time and O(1) space.',
    iconName: 'Shuffle',
    category: 'SEARCHING_SORTING',
    order: 6,
    track: 'CAMPUS_DSA',
  },

  // ── TREES & HEAPS ──
  {
    id: 'dsa-inplace-linkedlist',
    title: 'In-place Reversal of LinkedList',
    cluster: 'Trees & Heaps',
    description: 'Reverse linked list, reverse nodes in k-group, and palindrome linked list verification.',
    iconName: 'GitMerge',
    category: 'LINKED_LISTS',
    order: 7,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-tree-bfs',
    title: 'Tree BFS & Level Order Traversal',
    cluster: 'Trees & Heaps',
    description: 'Level order traversal, zigzag traversal, right/left side view, and minimum depth of binary tree.',
    iconName: 'Binary',
    category: 'TREES_BINARY_TREES',
    order: 8,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-tree-dfs',
    title: 'Tree DFS & Path Sums',
    cluster: 'Trees & Heaps',
    description: 'Inorder/Preorder/Postorder, path sum validation, diameter of binary tree, and lowest common ancestor.',
    iconName: 'Brain',
    category: 'TREES_BINARY_TREES',
    order: 9,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-two-heaps',
    title: 'Two Heaps & Median Tracking',
    cluster: 'Trees & Heaps',
    description: 'Find median from data stream, sliding window median, and maximize capital with dual heaps.',
    iconName: 'Cpu',
    category: 'STACKS_QUEUES',
    order: 10,
    track: 'CAMPUS_DSA',
  },

  // ── BACKTRACKING, DP & GRAPHS ──
  {
    id: 'dsa-subsets-backtracking',
    title: 'Subsets, Combinations & Backtracking',
    cluster: 'Backtracking, DP & Graphs',
    description: 'Power set generation, permutations with duplicates, combination sum, and N-Queens.',
    iconName: 'Code2',
    category: 'RECURSION',
    order: 11,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-modified-binary-search',
    title: 'Modified Binary Search',
    cluster: 'Backtracking, DP & Graphs',
    description: 'Search in rotated sorted array, find peak element, single non-duplicate in sorted array.',
    iconName: 'Search',
    category: 'SEARCHING_SORTING',
    order: 12,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-top-k-elements',
    title: 'Top \'K\' Elements & Priority Queues',
    cluster: 'Backtracking, DP & Graphs',
    description: 'Kth largest element, top K frequent elements, sort characters by frequency using Min/Max Heap.',
    iconName: 'Sparkles',
    category: 'STACKS_QUEUES',
    order: 13,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-01-knapsack-dp',
    title: '0/1 Knapsack & Dynamic Programming',
    cluster: 'Backtracking, DP & Graphs',
    description: 'Subset sum, partition equal subset sum, coin change, and classic memoized 0/1 knapsack.',
    iconName: 'Terminal',
    category: 'DYNAMIC_PROGRAMMING',
    order: 14,
    track: 'CAMPUS_DSA',
  },
  {
    id: 'dsa-topological-sort',
    title: 'Topological Sort & Course Schedule',
    cluster: 'Backtracking, DP & Graphs',
    description: 'Course Schedule I & II, alien dictionary, cycle detection in directed graphs using Kahn\'s algorithm.',
    iconName: 'Layers',
    category: 'SEARCHING_SORTING',
    order: 15,
    track: 'CAMPUS_DSA',
  },
];

// ============================================================================
// TECHNICAL MCQS: INDIA BIX STANDARD SUBJECT DIRECTORY
// ============================================================================
export const TECHNICAL_MCQ_TOPICS: ProgrammingTopic[] = [
  // ── PROGRAMMING LANGUAGES ──
  {
    id: 'mcq-c-programming',
    title: 'C Programming',
    cluster: 'Programming Languages',
    description: 'Pointers, arrays, structures, storage classes, preprocessor directives, and memory allocation.',
    iconName: 'Terminal',
    category: 'SYNTAX_BASICS',
    order: 1,
    track: 'TECHNICAL_MCQS',
  },
  {
    id: 'mcq-cpp-programming',
    title: 'C++ Programming',
    cluster: 'Programming Languages',
    description: 'OOP concepts, constructors/destructors, virtual functions, templates, STL, and operator overloading.',
    iconName: 'Code2',
    category: 'SYNTAX_BASICS',
    order: 2,
    track: 'TECHNICAL_MCQS',
  },
  {
    id: 'mcq-csharp-programming',
    title: 'C# Programming',
    cluster: 'Programming Languages',
    description: 'CLR, garbage collection, value vs reference types, delegates & events, LINQ, and async/await.',
    iconName: 'Hash',
    category: 'SYNTAX_BASICS',
    order: 3,
    track: 'TECHNICAL_MCQS',
  },
  {
    id: 'mcq-java-programming',
    title: 'Java Programming',
    cluster: 'Programming Languages',
    description: 'String pool & immutability, collections framework, multithreading, exception handling, and JVM.',
    iconName: 'Code2',
    category: 'SYNTAX_BASICS',
    order: 4,
    track: 'TECHNICAL_MCQS',
  },

  // ── CORE COMPUTER SCIENCE ──
  {
    id: 'mcq-database',
    title: 'Database (DBMS & SQL)',
    cluster: 'Core CS Subjects',
    description: 'Normalization (1NF-BCNF), ACID properties, transactions & locking, SQL joins, and indexing.',
    iconName: 'Database',
    category: 'ARRAYS',
    order: 5,
    track: 'TECHNICAL_MCQS',
  },
  {
    id: 'mcq-networking',
    title: 'Computer Networks',
    cluster: 'Core CS Subjects',
    description: 'OSI & TCP/IP layers, subnet mask calculation, routing protocols, DNS/HTTP/TCP handshake, and ARP.',
    iconName: 'Network',
    category: 'SYNTAX_BASICS',
    order: 6,
    track: 'TECHNICAL_MCQS',
  },
  {
    id: 'mcq-operating-systems',
    title: 'Operating Systems',
    cluster: 'Core CS Subjects',
    description: 'Process scheduling, memory management & paging, semaphores & deadlocks, virtual memory, and fork().',
    iconName: 'Server',
    category: 'SYNTAX_BASICS',
    order: 7,
    track: 'TECHNICAL_MCQS',
  },

  // ── CAMPUS OA & STRUCTURES ──
  {
    id: 'mcq-data-structures',
    title: 'Data Structures',
    cluster: 'Campus OA & Structures',
    description: 'Arrays, stacks, queues, linked lists, binary search trees, heaps, graphs, and hashing techniques.',
    iconName: 'Layers',
    category: 'ARRAYS',
    order: 8,
    track: 'TECHNICAL_MCQS',
  },
  {
    id: 'mcq-pseudo-code',
    title: 'Campus OA Pseudo-Code',
    cluster: 'Campus OA & Structures',
    description: 'Accenture, Capgemini, and Cognizant pseudo-code dry-runs, bitwise operators, and recursive calls.',
    iconName: 'Cpu',
    category: 'BIT_MANIPULATION',
    order: 9,
    track: 'TECHNICAL_MCQS',
  },
];

export const PROGRAMMING_150_EXPANDED_SEED: ProgrammingProblem[] = [];
