// Dedicated Topic Slug Resolution Map
// Maps raw user import strings / topic names to canonical URL slugs

export const TOPIC_SLUG_MAP: Readonly<Record<string, string>> = Object.freeze({
  // Data Interpretation
  'table charts': 'table-charts',
  'table chart': 'table-charts',
  'tables': 'table-charts',
  'bar charts': 'bar-charts',
  'bar chart': 'bar-charts',
  'bars': 'bar-charts',
  'pie charts': 'pie-charts',
  'pie chart': 'pie-charts',
  'line charts': 'line-charts',
  'line chart': 'line-charts',

  // Verbal Ability
  'spotting errors': 'spotting-errors',
  'error spotting': 'spotting-errors',
  'antonyms': 'antonyms',
  'synonyms': 'synonyms',
  'spellings': 'spellings',
  'spelling test': 'spellings',
  'ordering of words': 'ordering-of-words',
  'word order': 'ordering-of-words',
  'sentence improvement': 'sentence-improvement',
  'ordering of sentences': 'ordering-of-sentences',
  'sentence ordering': 'ordering-of-sentences',
  'cloze test': 'cloze-test',
  'closet test': 'cloze-test',
  'selecting words': 'selecting-words',
  'sentence formation': 'sentence-formation',
  'sentence correction': 'sentence-correction',
  'one word substitutes': 'one-word-substitutes',
  'one word substitution': 'one-word-substitutes',
  'change of voice': 'change-of-voice',
  'voice': 'change-of-voice',
  'verbal analogies': 'verbal-analogies',
  'completing statements': 'completing-statements',
  'paragraph formation': 'paragraph-formation',
  'comprehension': 'reading-comprehension',
  'reading comprehension': 'reading-comprehension',
  'idioms and phrases': 'idioms-and-phrases',
  'idioms & phrases': 'idioms-and-phrases',
  'change of speech': 'change-of-speech',
  'direct and indirect speech': 'change-of-speech',

  // Logical Reasoning & Verbal Reasoning
  'number series': 'number-series',
  'verbal classification': 'verbal-classification',
  'analogies': 'analogies',
  'matching definitions': 'matching-definitions',
  'verbal reasoning': 'verbal-reasoning',
  'logical games': 'logical-games',
  'statement and assumption': 'statement-and-assumption',
  'statement and conclusion': 'statement-and-conclusion',
  'cause and effect': 'cause-and-effect',
  'letter and symbol series': 'letter-and-symbol-series',
  'essential part': 'essential-part',
  'artificial language': 'artificial-language',
  'making judgments': 'making-judgments',
  'logical problems': 'logical-problems',
  'analyzing arguments': 'analyzing-arguments',
  'course of action': 'course-of-action',
  'theme detection': 'theme-detection',
  'statement and argument': 'statement-and-argument',
  'logical deduction': 'logical-deduction',
  'logical sequence of words': 'logical-sequence-of-words',
  'syllogism': 'syllogism',
  'syllogisms': 'syllogism',
  'venn diagrams': 'venn-diagrams',
  'character puzzles': 'character-puzzles',
  'classification': 'classification',
  'blood relation test': 'blood-relation-test',
  'blood relations': 'blood-relation-test',
  'series completion': 'series-completion',
  'dice': 'dice',
  'cube and cuboid': 'cube-and-cuboid',
  'seating arrangement': 'seating-arrangement',
  'direction sense test': 'direction-sense-test',
  'direction sense': 'direction-sense-test',
  'data sufficiency': 'data-sufficiency',
  'arithmetic reasoning': 'arithmetic-reasoning',

  // Arithmetic Aptitude
  'numbers': 'numbers',
  'number system': 'numbers',
  'hcf and lcm': 'hcf-and-lcm',
  'lcm and hcf': 'hcf-and-lcm',
  'simplification': 'simplification',
  'percentage': 'percentage',
  'percentages': 'percentage',
  'profit and loss': 'profit-and-loss',
  'ratio and proportion': 'ratio-and-proportion',
  'ratios': 'ratio-and-proportion',
  'average': 'averages',
  'averages': 'averages',
  'simple interest': 'simple-interest',
  'compound interest': 'compound-interest',
  'time and work': 'time-and-work',
  'pipes and cisterns': 'pipes-and-cisterns',
  'time and distance': 'time-and-distance',
  'speed time distance': 'time-and-distance',
  'problems on trains': 'problems-on-trains',
  'trains': 'problems-on-trains',
  'boats and streams': 'boats-and-streams',
  'alligation or mixture': 'alligation-or-mixture',
  'mixtures': 'alligation-or-mixture',
  'problems on ages': 'problems-on-ages',
  'ages': 'problems-on-ages',
  'surds and indices': 'surds-and-indices',
  'area': 'area',
  'volume and surface area': 'volume-and-surface-area',
  'races and games': 'races-and-games',
  'stocks and shares': 'stocks-and-shares',
  'probability': 'probability',
  'permutation and combination': 'permutation-and-combination',
  'permutations': 'permutation-and-combination',
  'clocks': 'clocks',
  'calendar': 'calendar',
  'logarithms': 'logarithms',

  // Nonverbal Reasoning
  'mirror images': 'mirror-images',
  'water images': 'water-images',
  'pattern completion': 'pattern-completion',
  'paper folding': 'paper-folding',
  'paper cutting': 'paper-cutting',
  'rule detection': 'rule-detection',
  'figure matrix': 'figure-matrix',
  'embedded images': 'embedded-images',
});

export function resolveTopicSlug(topicName?: string, defaultTopicId: string = 'numbers'): string {
  if (!topicName || !topicName.trim()) return defaultTopicId;
  const sanitized = topicName.trim().toLowerCase();
  if (TOPIC_SLUG_MAP[sanitized]) return TOPIC_SLUG_MAP[sanitized];

  // Slugify fallback
  const slugified = sanitized
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
    
  return slugified || defaultTopicId;
}
