// Dedicated Topic Slug Resolution Map
// Maps raw user import strings / topic names to canonical URL slugs

export const TOPIC_SLUG_MAP: Readonly<Record<string, string>> = Object.freeze({
  // Data Interpretation
  'table charts': 'table-charts',
  'table chart': 'table-charts',
  'tables': 'table-charts',
  'bar charts': 'bar-charts',
  'bar chart': 'bar-charts',
  'bars': 'bar-charts',
  'pie charts': 'pie-charts',
  'pie chart': 'pie-charts',
  'line charts': 'line-charts',
  'line chart': 'line-charts',

  // Verbal Ability
  'verbal ability': 'verbal-ability',
  'english': 'verbal-ability',
  'spotting errors': 'spotting-errors',
  'error spotting': 'spotting-errors',
  'antonyms': 'antonyms',
  'synonyms': 'synonyms',
  'spellings': 'spellings',
  'spelling test': 'spellings',
  'ordering of words': 'ordering-of-words',
  'word order': 'ordering-of-words',
  'sentence improvement': 'sentence-improvement',
  'ordering of sentences': 'ordering-of-sentences',
  'sentence ordering': 'ordering-of-sentences',
  'cloze test': 'cloze-test',
  'closet test': 'cloze-test',
  'selecting words': 'selecting-words',
  'sentence formation': 'sentence-formation',
  'sentence correction': 'sentence-correction',
  'one word substitutes': 'one-word-substitutes',
  'one word substitution': 'one-word-substitutes',
  'change of voice': 'change-of-voice',
  'voice': 'change-of-voice',
  'verbal analogies': 'verbal-analogies',
  'completing statements': 'completing-statements',
  'paragraph formation': 'paragraph-formation',
  'comprehension': 'reading-comprehension',
  'reading comprehension': 'reading-comprehension',
  'idioms and phrases': 'idioms-and-phrases',
  'idioms & phrases': 'idioms-and-phrases',
  'change of speech': 'change-of-speech',
  'direct and indirect speech': 'change-of-speech',

  // Logical Reasoning & Verbal Reasoning
  'number series': 'number-series',
  'verbal classification': 'verbal-classification',
  'analogies': 'analogies',
  'matching definitions': 'matching-definitions',
  'verbal reasoning': 'verbal-reasoning',
  'logical games': 'logical-games',
  'statement and assumption': 'statement-and-assumption',
  'statement and conclusion': 'statement-and-conclusion',
  'cause and effect': 'cause-and-effect',
  'letter and symbol series': 'letter-and-symbol-series',
  'essential part': 'essential-part',
  'artificial language': 'artificial-language',
  'making judgments': 'making-judgments',
  'logical problems': 'logical-problems',
  'analyzing arguments': 'analyzing-arguments',
  'course of action': 'course-of-action',
  'theme detection': 'theme-detection',
  'statement and argument': 'statement-and-argument',
  'logical deduction': 'logical-deduction',
  'logical sequence of words': 'logical-sequence-of-words',
  'syllogism': 'syllogisms',
  'syllogisms': 'syllogisms',
  'venn diagrams': 'venn-diagrams',
  'character puzzles': 'character-puzzles',
  'classification': 'classification',
  'blood relation test': 'blood-relations',
  'blood relations': 'blood-relations',
  'blood-relations': 'blood-relations',
  'blood-relation-test': 'blood-relations',
  'series completion': 'series-completion',
  'dice': 'cubes-and-dice',
  'cube and cuboid': 'cubes-and-dice',
  'cubes and dice': 'cubes-and-dice',
  'cubes-and-dice': 'cubes-and-dice',
  'seating arrangement': 'seating-arrangement',
  'direction sense test': 'direction-sense',
  'direction sense': 'direction-sense',
  'direction-sense': 'direction-sense',
  'direction-sense-test': 'direction-sense',
  'data sufficiency': 'data-sufficiency',
  'arithmetic reasoning': 'arithmetic-reasoning',

  // Arithmetic Aptitude
  'numbers': 'numbers',
  'number system': 'numbers',
  'problems on numbers': 'problems-on-numbers',
  'problems-on-numbers': 'problems-on-numbers',
  'hcf and lcm': 'hcf-lcm',
  'hcf & lcm': 'hcf-lcm',
  'lcm and hcf': 'hcf-lcm',
  'lcm & hcf': 'hcf-lcm',
  'hcf-lcm': 'hcf-lcm',
  'hcf-and-lcm': 'hcf-lcm',
  'problems on hcf and lcm': 'hcf-lcm',
  'problems on h.c.f and l.c.m': 'hcf-lcm',
  'problems on h.c.f. and l.c.m.': 'hcf-lcm',
  'problems on hcf & lcm': 'hcf-lcm',
  'decimal fraction': 'decimal-fraction',
  'decimal fractions': 'decimal-fraction',
  'decimal-fraction': 'decimal-fraction',
  'simplification': 'simplification',
  'square root and cube root': 'square-cube-root',
  'square and cube root': 'square-cube-root',
  'square-cube-root': 'square-cube-root',
  'percentage': 'percentage',
  'percentages': 'percentage',
  'profit and loss': 'profit-and-loss',
  'ratio and proportion': 'ratio-and-proportion',
  'ratios': 'ratio-and-proportion',
  'average': 'average',
  'averages': 'average',
  'simple interest': 'simple-interest',
  'compound interest': 'compound-interest',
  'partnership': 'partnership',
  'time and work': 'time-and-work',
  'pipes and cistern': 'pipes-and-cistern',
  'pipes and cisterns': 'pipes-and-cistern',
  'pipes & cisterns': 'pipes-and-cistern',
  'pipes & cistern': 'pipes-and-cistern',
  'pipes-and-cistern': 'pipes-and-cistern',
  'pipes-and-cisterns': 'pipes-and-cistern',
  'time and distance': 'time-and-distance',
  'speed time distance': 'time-and-distance',
  'problems on trains': 'problems-on-trains',
  'trains': 'problems-on-trains',
  'boats and streams': 'boats-and-streams',
  'chain rule': 'chain-rule',
  'chain-rule': 'chain-rule',
  'alligation or mixture': 'alligation-or-mixture',
  'mixtures': 'alligation-or-mixture',
  'problems on ages': 'problems-on-ages',
  'ages': 'problems-on-ages',
  'surds and indices': 'surds-and-indices',
  'area': 'area',
  'volume and surface area': 'volume-and-surface-area',
  'races and games': 'races-and-games',
  'stocks and shares': 'stocks-and-shares',
  'true discount': 'true-discount',
  'true-discount': 'true-discount',
  'bankers discount': 'bankers-discount',
  'banker\'s discount': 'bankers-discount',
  'bankers-discount': 'bankers-discount',
  'probability': 'probability',
  'permutation and combination': 'permutation-and-combination',
  'permutations': 'permutation-and-combination',
  'clock': 'clock',
  'clocks': 'clock',
  'calendar': 'calendar',
  'logarithm': 'logarithm',
  'logarithms': 'logarithm',

  // Nonverbal Reasoning
  'mirror images': 'mirror-images',
  'water images': 'water-images',
  'pattern completion': 'pattern-completion',
  'paper folding': 'paper-folding',
  'paper cutting': 'paper-cutting',
  'rule detection': 'rule-detection',
  'figure matrix': 'figure-matrix',
  'embedded images': 'embedded-images',
  'dot situation': 'dot-situation',
  'dot situation test': 'dot-situation',
  'counting of figures': 'counting-of-figures',
  'counting figures': 'counting-of-figures',
  'figure counting': 'counting-of-figures',
  'grouping of images': 'grouping-of-images',
  'grouping of identical figures': 'grouping-of-images',
  'shape construction': 'shape-construction',
  'shape construction & reconstruction': 'shape-construction',
  'shape construction and reconstruction': 'shape-construction',
  'nonverbal analogy': 'nonverbal-analogy',
  'non-verbal analogy': 'nonverbal-analogy',
  'nonverbal classification': 'nonverbal-classification',
  'non-verbal classification': 'nonverbal-classification',

  // Higher Maths & Algebra
  'algebra': 'algebra-quadratic-equations',
  'quadratic equations': 'algebra-quadratic-equations',
  'algebra and quadratic equations': 'algebra-quadratic-equations',
  'algebra & quadratic equations': 'algebra-quadratic-equations',
  'progressions': 'progressions-ap-gp-hp',
  'progressions ap gp hp': 'progressions-ap-gp-hp',
  'ap gp hp': 'progressions-ap-gp-hp',
  'sequence and series': 'progressions-ap-gp-hp',
  'arithmetic progression': 'progressions-ap-gp-hp',
  'geometric progression': 'progressions-ap-gp-hp',
  'set theory': 'set-theory',
  'set theory and venn math': 'set-theory',
  'set theory & venn math': 'set-theory',
  'geometry': 'geometry-theorems',
  'geometry and polygons': 'geometry-theorems',
  'geometry & polygons': 'geometry-theorems',
  'polygons': 'geometry-theorems',
  'coordinate geometry': 'coordinate-geometry',
  'co-ordinate geometry': 'coordinate-geometry',
  'trigonometry': 'trigonometry',
  'trigonometry and identities': 'trigonometry',
  'trigonometry & identities': 'trigonometry',

  // Advanced DI
  'radar charts': 'radar-web-charts',
  'radar web charts': 'radar-web-charts',
  'radar & spider web charts': 'radar-web-charts',
  'spider charts': 'radar-web-charts',
  'scatter plots': 'scatter-bubble-charts',
  'scatter and bubble charts': 'scatter-bubble-charts',
  'scatter & bubble charts': 'scatter-bubble-charts',
  'scatter plots & bubble charts': 'scatter-bubble-charts',
  'missing di': 'missing-di',
  'missing data interpretation': 'missing-di',

  // Advanced Placement Logic Puzzles
  'cryptarithmetic': 'cryptarithmetic',
  'alphametics': 'cryptarithmetic',
  'cryptarithmetic (alphametics)': 'cryptarithmetic',
  'machine input output': 'machine-input-output',
  'machine input-output': 'machine-input-output',
  'input output': 'machine-input-output',
  'inequalities': 'inequalities',
  'mathematical inequalities': 'inequalities',
  'coded inequalities': 'inequalities',
  'mathematical & coded inequalities': 'inequalities',
  'order and ranking': 'order-and-ranking',
  'order & ranking': 'order-and-ranking',
  'ranking': 'order-and-ranking',
  'floor puzzles': 'floor-scheduling-puzzles',
  'scheduling puzzles': 'floor-scheduling-puzzles',
  'floor & scheduling puzzles': 'floor-scheduling-puzzles',
  'floor and scheduling puzzles': 'floor-scheduling-puzzles',
  'games and tournaments': 'games-and-tournaments',
  'games & tournaments': 'games-and-tournaments',
  'tournaments': 'games-and-tournaments',
  'truth tellers and liars': 'truth-tellers-liars',
  'truth tellers & liars': 'truth-tellers-liars',
  'truth-tellers and liars': 'truth-tellers-liars',
  'binary logic': 'truth-tellers-liars',
  'eligibility test': 'eligibility-test',
  'decision making': 'eligibility-test',
  'eligibility test & decision making': 'eligibility-test',
  'assertion and reason': 'assertion-and-reason',
  'assertion & reason': 'assertion-and-reason',
  'statement and inferences': 'statement-and-inferences',
  'statement & inferences': 'statement-and-inferences',
  'inferences': 'statement-and-inferences',

  // Modern Verbal Additions
  'confusing words': 'confusing-words',
  'homophones': 'confusing-words',
  'confusing words & homophones': 'confusing-words',
  'double fillers': 'double-fillers',
  'double fillers and connectors': 'double-fillers',
  'double fillers & connectors': 'double-fillers',
  'sentence connectors': 'double-fillers',

  // Technical & Cognitive Aptitude
  'technical aptitude': 'technical-aptitude',
  'pseudocode': 'pseudocode-tracing',
  'pseudocode tracing': 'pseudocode-tracing',
  'pseudocode & variable tracing': 'pseudocode-tracing',
  'bitwise operators': 'bitwise-operators',
  'bitwise operators & logic': 'bitwise-operators',
  'bitwise logic': 'bitwise-operators',
  'recursion': 'recursion-functions',
  'recursion & function scope': 'recursion-functions',
  'recursion and function scope': 'recursion-functions',
  'attention to detail': 'attention-to-detail',
  'attention to detail & visual checking': 'attention-to-detail',
  'visual checking': 'attention-to-detail',
  'code debugging': 'code-debugging-logic',
  'code debugging & automata fix': 'code-debugging-logic',
  'automata fix': 'code-debugging-logic',
  'cloud basics': 'cloud-networking-basics',
  'general tech': 'cloud-networking-basics',
  'general tech, os & cloud basics': 'cloud-networking-basics',
  'cloud & networking basics': 'cloud-networking-basics',
});

export function resolveTopicSlug(topicName?: string, defaultTopicId: string = 'numbers'): string {
  if (!topicName || !topicName.trim()) return defaultTopicId;
  const sanitized = topicName.trim().toLowerCase();
  if (TOPIC_SLUG_MAP[sanitized]) return TOPIC_SLUG_MAP[sanitized];

  // Slugify fallback
  const slugified = sanitized
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
    
  return slugified || defaultTopicId;
}
