// Dedicated Topic Slug Resolution Map
// Maps raw user import strings / topic names to canonical URL slugs

export const TOPIC_SLUG_MAP: Readonly<Record<string, string>> = Object.freeze({
  // Data Interpretation
  'table charts': 'table-charts',
  'table chart': 'table-charts',
  'tables': 'table-charts',
  'bar charts': 'bar-charts',
  'bar chart': 'bar-charts',
  'bars': 'bar-charts',
  'pie charts': 'pie-charts',
  'pie chart': 'pie-charts',
  'line charts': 'line-charts',
  'line chart': 'line-charts',

  // Verbal Ability
  'verbal ability': 'verbal-ability',
  'english': 'verbal-ability',
  'spotting errors': 'spotting-errors',
  'error spotting': 'spotting-errors',
  'antonyms': 'antonyms',
  'synonyms': 'synonyms',
  'spellings': 'spellings',
  'spelling test': 'spellings',
  'ordering of words': 'ordering-of-words',
  'word order': 'ordering-of-words',
  'sentence improvement': 'sentence-improvement',
  'ordering of sentences': 'ordering-of-sentences',
  'sentence ordering': 'ordering-of-sentences',
  'cloze test': 'cloze-test',
  'closet test': 'cloze-test',
  'selecting words': 'selecting-words',
  'sentence formation': 'sentence-formation',
  'sentence correction': 'sentence-correction',
  'one word substitutes': 'one-word-substitutes',
  'one word substitution': 'one-word-substitutes',
  'change of voice': 'change-of-voice',
  'voice': 'change-of-voice',
  'verbal analogies': 'verbal-analogies',
  'completing statements': 'completing-statements',
  'paragraph formation': 'paragraph-formation',
  'comprehension': 'reading-comprehension',
  'reading comprehension': 'reading-comprehension',
  'idioms and phrases': 'idioms-and-phrases',
  'idioms & phrases': 'idioms-and-phrases',
  'change of speech': 'change-of-speech',
  'direct and indirect speech': 'change-of-speech',

  // Logical Reasoning & Verbal Reasoning
  'number series': 'number-series',
  'verbal classification': 'verbal-classification',
  'analogies': 'analogies',
  'matching definitions': 'matching-definitions',
  'verbal reasoning': 'verbal-reasoning',
  'logical games': 'logical-games',
  'statement and assumption': 'statement-and-assumption',
  'statement and conclusion': 'statement-and-conclusion',
  'cause and effect': 'cause-and-effect',
  'letter and symbol series': 'letter-and-symbol-series',
  'essential part': 'essential-part',
  'artificial language': 'artificial-language',
  'making judgments': 'making-judgments',
  'logical problems': 'logical-problems',
  'analyzing arguments': 'analyzing-arguments',
  'course of action': 'course-of-action',
  'theme detection': 'theme-detection',
  'statement and argument': 'statement-and-argument',
  'logical deduction': 'logical-deduction',
  'logical sequence of words': 'logical-sequence-of-words',
  'syllogism': 'syllogisms',
  'syllogisms': 'syllogisms',
  'venn diagrams': 'venn-diagrams',
  'character puzzles': 'character-puzzles',
  'classification': 'classification',
  'blood relation test': 'blood-relations',
  'blood relations': 'blood-relations',
  'blood-relations': 'blood-relations',
  'blood-relation-test': 'blood-relations',
  'series completion': 'series-completion',
  'dice': 'cubes-and-dice',
  'cube and cuboid': 'cubes-and-dice',
  'cubes and dice': 'cubes-and-dice',
  'cubes-and-dice': 'cubes-and-dice',
  'seating arrangement': 'seating-arrangement',
  'direction sense test': 'direction-sense',
  'direction sense': 'direction-sense',
  'direction-sense': 'direction-sense',
  'direction-sense-test': 'direction-sense',
  'data sufficiency': 'data-sufficiency',
  'arithmetic reasoning': 'arithmetic-reasoning',

  // Arithmetic Aptitude
  'numbers': 'numbers',
  'number system': 'numbers',
  'problems on numbers': 'problems-on-numbers',
  'problems-on-numbers': 'problems-on-numbers',
  'hcf and lcm': 'hcf-lcm',
  'hcf & lcm': 'hcf-lcm',
  'lcm and hcf': 'hcf-lcm',
  'lcm & hcf': 'hcf-lcm',
  'hcf-lcm': 'hcf-lcm',
  'hcf-and-lcm': 'hcf-lcm',
  'problems on hcf and lcm': 'hcf-lcm',
  'problems on h.c.f and l.c.m': 'hcf-lcm',
  'problems on h.c.f. and l.c.m.': 'hcf-lcm',
  'problems on hcf & lcm': 'hcf-lcm',
  'decimal fraction': 'decimal-fraction',
  'decimal fractions': 'decimal-fraction',
  'decimal-fraction': 'decimal-fraction',
  'simplification': 'simplification',
  'square root and cube root': 'square-cube-root',
  'square and cube root': 'square-cube-root',
  'square-cube-root': 'square-cube-root',
  'percentage': 'percentage',
  'percentages': 'percentage',
  'profit and loss': 'profit-and-loss',
  'ratio and proportion': 'ratio-and-proportion',
  'ratios': 'ratio-and-proportion',
  'average': 'average',
  'averages': 'average',
  'simple interest': 'simple-interest',
  'compound interest': 'compound-interest',
  'partnership': 'partnership',
  'time and work': 'time-and-work',
  'pipes and cistern': 'pipes-and-cistern',
  'pipes and cisterns': 'pipes-and-cistern',
  'pipes & cisterns': 'pipes-and-cistern',
  'pipes & cistern': 'pipes-and-cistern',
  'pipes-and-cistern': 'pipes-and-cistern',
  'pipes-and-cisterns': 'pipes-and-cistern',
  'time and distance': 'time-and-distance',
  'speed time distance': 'time-and-distance',
  'problems on trains': 'problems-on-trains',
  'trains': 'problems-on-trains',
  'boats and streams': 'boats-and-streams',
  'chain rule': 'chain-rule',
  'chain-rule': 'chain-rule',
  'alligation or mixture': 'alligation-or-mixture',
  'mixtures': 'alligation-or-mixture',
  'problems on ages': 'problems-on-ages',
  'ages': 'problems-on-ages',
  'surds and indices': 'surds-and-indices',
  'area': 'area',
  'volume and surface area': 'volume-and-surface-area',
  'races and games': 'races-and-games',
  'stocks and shares': 'stocks-and-shares',
  'true discount': 'true-discount',
  'true-discount': 'true-discount',
  'bankers discount': 'bankers-discount',
  'banker\'s discount': 'bankers-discount',
  'bankers-discount': 'bankers-discount',
  'probability': 'probability',
  'permutation and combination': 'permutation-and-combination',
  'permutations': 'permutation-and-combination',
  'clock': 'clock',
  'clocks': 'clock',
  'calendar': 'calendar',
  'logarithm': 'logarithm',
  'logarithms': 'logarithm',

  // Nonverbal Reasoning
  'mirror images': 'mirror-images',
  'water images': 'water-images',
  'pattern completion': 'pattern-completion',
  'visual series': 'pattern-completion',
  'visual series & pattern completion': 'pattern-completion',
  'visual series and pattern completion': 'pattern-completion',
  'paper folding': 'paper-folding',
  'paper cutting': 'paper-cutting',
  'rule detection': 'rule-detection',
  'figure matrix': 'figure-matrix',
  'embedded images': 'embedded-images',
  'dot situation': 'dot-situation',
  'dot situation test': 'dot-situation',
  'counting of figures': 'counting-of-figures',
  'counting figures': 'counting-of-figures',
  'figure counting': 'counting-of-figures',
  'grouping of images': 'grouping-of-images',
  'grouping of identical figures': 'grouping-of-images',
  'shape construction': 'shape-construction',
  'shape construction & reconstruction': 'shape-construction',
  'shape construction and reconstruction': 'shape-construction',
  'nonverbal analogy': 'nonverbal-analogy',
  'non-verbal analogy': 'nonverbal-analogy',
  'nonverbal classification': 'nonverbal-classification',
  'non-verbal classification': 'nonverbal-classification',

  // Higher Maths & Algebra
  'algebra': 'algebra-quadratic-equations',
  'quadratic equations': 'algebra-quadratic-equations',
  'algebra and quadratic equations': 'algebra-quadratic-equations',
  'algebra & quadratic equations': 'algebra-quadratic-equations',
  'progressions': 'progressions-ap-gp-hp',
  'progressions ap gp hp': 'progressions-ap-gp-hp',
  'ap gp hp': 'progressions-ap-gp-hp',
  'sequence and series': 'progressions-ap-gp-hp',
  'arithmetic progression': 'progressions-ap-gp-hp',
  'geometric progression': 'progressions-ap-gp-hp',
  'set theory': 'set-theory',
  'set theory and venn math': 'set-theory',
  'set theory & venn math': 'set-theory',
  'geometry': 'geometry-theorems',
  'geometry and polygons': 'geometry-theorems',
  'geometry & polygons': 'geometry-theorems',
  'polygons': 'geometry-theorems',
  'coordinate geometry': 'coordinate-geometry',
  'co-ordinate geometry': 'coordinate-geometry',
  'trigonometry': 'trigonometry',
  'trigonometry and identities': 'trigonometry',
  'trigonometry & identities': 'trigonometry',

  // Advanced DI
  'radar charts': 'radar-web-charts',
  'radar web charts': 'radar-web-charts',
  'radar & spider web charts': 'radar-web-charts',
  'spider charts': 'radar-web-charts',
  'scatter plots': 'scatter-bubble-charts',
  'scatter and bubble charts': 'scatter-bubble-charts',
  'scatter & bubble charts': 'scatter-bubble-charts',
  'scatter plots & bubble charts': 'scatter-bubble-charts',
  'missing di': 'missing-di',
  'missing data interpretation': 'missing-di',

  // Advanced Placement Logic Puzzles
  'cryptarithmetic': 'cryptarithmetic',
  'alphametics': 'cryptarithmetic',
  'cryptarithmetic (alphametics)': 'cryptarithmetic',
  'machine input output': 'machine-input-output',
  'machine input-output': 'machine-input-output',
  'input output': 'machine-input-output',
  'inequalities': 'inequalities',
  'mathematical inequalities': 'inequalities',
  'coded inequalities': 'inequalities',
  'mathematical & coded inequalities': 'inequalities',
  'order and ranking': 'order-and-ranking',
  'order & ranking': 'order-and-ranking',
  'ranking': 'order-and-ranking',
  'floor puzzles': 'floor-scheduling-puzzles',
  'scheduling puzzles': 'floor-scheduling-puzzles',
  'floor & scheduling puzzles': 'floor-scheduling-puzzles',
  'floor and scheduling puzzles': 'floor-scheduling-puzzles',
  'games and tournaments': 'games-and-tournaments',
  'games & tournaments': 'games-and-tournaments',
  'tournaments': 'games-and-tournaments',
  'truth tellers and liars': 'truth-tellers-liars',
  'truth tellers & liars': 'truth-tellers-liars',
  'truth-tellers and liars': 'truth-tellers-liars',
  'binary logic': 'truth-tellers-liars',
  'eligibility test': 'eligibility-test',
  'decision making': 'eligibility-test',
  'eligibility test & decision making': 'eligibility-test',
  'assertion and reason': 'assertion-and-reason',
  'assertion & reason': 'assertion-and-reason',
  'statement and inferences': 'statement-and-inferences',
  'statement & inferences': 'statement-and-inferences',
  'inferences': 'statement-and-inferences',

  // Modern Verbal Additions
  'confusing words': 'confusing-words',
  'homophones': 'confusing-words',
  'confusing words & homophones': 'confusing-words',
  'double fillers': 'double-fillers',
  'double fillers and connectors': 'double-fillers',
  'double fillers & connectors': 'double-fillers',
  'sentence connectors': 'double-fillers',

  // Technical & Cognitive Aptitude
  'technical aptitude': 'technical-aptitude',
  'pseudocode': 'pseudocode-tracing',
  'pseudocode tracing': 'pseudocode-tracing',
  'pseudocode & variable tracing': 'pseudocode-tracing',
  'bitwise operators': 'bitwise-operators',
  'bitwise operators & logic': 'bitwise-operators',
  'bitwise logic': 'bitwise-operators',
  'recursion': 'recursion-functions',
  'recursion & function scope': 'recursion-functions',
  'recursion and function scope': 'recursion-functions',
  'attention to detail': 'attention-to-detail',
  'attention to detail & visual checking': 'attention-to-detail',
  'visual checking': 'attention-to-detail',
  'code debugging': 'code-debugging-logic',
  'code debugging & automata fix': 'code-debugging-logic',
  'automata fix': 'code-debugging-logic',
  'cloud basics': 'cloud-networking-basics',
  'general tech': 'cloud-networking-basics',
  'general tech, os & cloud basics': 'cloud-networking-basics',
  'cloud & networking basics': 'cloud-networking-basics',
});

export function resolveTopicSlug(topicName?: string, defaultTopicId: string = 'numbers'): string {
  if (!topicName || !topicName.trim()) return defaultTopicId;
  const sanitized = topicName.trim().toLowerCase();
  if (TOPIC_SLUG_MAP[sanitized]) return TOPIC_SLUG_MAP[sanitized];

  // Slugify fallback
  const slugified = sanitized
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
    
  return slugified || defaultTopicId;
}

export const TOPIC_ALIAS_FAMILIES: Readonly<Record<string, string[]>> = Object.freeze({
  // Arithmetic Aptitude
  'numbers': ['numbers', 'number-system', 'problems-on-numbers', 'num'],
  'problems-on-numbers': ['problems-on-numbers', 'numbers', 'number-system'],
  'hcf-lcm': ['hcf-lcm', 'hcf-and-lcm', 'lcm-and-hcf', 'hcf_lcm'],
  'decimal-fraction': ['decimal-fraction', 'decimal-fractions', 'decimals'],
  'simplification': ['simplification', 'simplifications'],
  'square-cube-root': ['square-cube-root', 'square-roots', 'cube-roots', 'square-root-and-cube-root'],
  'percentage': ['percentage', 'percentages', 'percent'],
  'profit-and-loss': ['profit-and-loss', 'profit-loss', 'profit_and_loss'],
  'ratio-and-proportion': ['ratio-and-proportion', 'ratio', 'ratios', 'ratio-proportion', 'ratio_and_proportion'],
  'partnership': ['partnership', 'partnerships'],
  'chain-rule': ['chain-rule', 'chain_rule'],
  'time-and-work': ['time-and-work', 'time-work', 'work-and-time', 'time_and_work', 'pipes-and-cistern'],
  'pipes-and-cistern': ['pipes-and-cistern', 'pipes-and-cisterns', 'pipes-cistern', 'pipes_and_cistern', 'time-and-work'],
  'time-and-distance': ['time-and-distance', 'time-distance', 'speed-time-distance', 'time_and_distance'],
  'problems-on-trains': ['problems-on-trains', 'trains', 'problems-trains', 'problems_on_trains', 'time-and-distance'],
  'boats-and-streams': ['boats-and-streams', 'boats-streams', 'boats_and_streams'],
  'alligation-or-mixture': ['alligation-or-mixture', 'alligation-and-mixture', 'alligation', 'mixtures'],
  'simple-interest': ['simple-interest', 'si', 'simple_interest'],
  'compound-interest': ['compound-interest', 'ci', 'compound_interest'],
  'stocks-and-shares': ['stocks-and-shares', 'stocks-shares', 'stocks'],
  'true-discount': ['true-discount', 'true_discount'],
  'bankers-discount': ['bankers-discount', 'banker-discount', 'bankers_discount'],
  'geometry-theorems': ['geometry-theorems', 'geometry', 'polygons'],
  'height-and-distance': ['height-and-distance', 'heights-and-distances', 'height-distance', 'hd'],
  'area': ['area', 'area-and-perimeter', 'perimeter'],
  'volume-and-surface-area': ['volume-and-surface-area', 'volume-surface-area', 'mensuration'],
  'coordinate-geometry': ['coordinate-geometry', 'co-ordinate-geometry'],
  'trigonometry': ['trigonometry', 'trigonometric-identities'],
  'algebra-quadratic-equations': ['algebra-quadratic-equations', 'algebra', 'quadratic-equations'],
  'progressions-ap-gp-hp': ['progressions-ap-gp-hp', 'progressions', 'ap-gp-hp', 'sequences-series'],
  'set-theory': ['set-theory', 'sets', 'venn-math'],
  'races-and-games': ['races-and-games', 'races-games', 'races'],
  'permutation-and-combination': ['permutation-and-combination', 'permutations-and-combinations', 'pnc', 'permutation_and_combination'],
  'probability': ['probability', 'probabilities'],
  'average': ['average', 'averages'],
  'problems-on-ages': ['problems-on-ages', 'ages', 'problems-ages'],
  'calendar': ['calendar', 'calendars'],
  'clock': ['clock', 'clocks'],
  'odd-man-out-and-series': ['odd-man-out-and-series', 'odd-man-out', 'series'],
  'surds-and-indices': ['surds-and-indices', 'surds-indices', 'surds', 'indices'],
  'surds-indices': ['surds-and-indices', 'surds-indices', 'surds', 'indices'],
  'logarithm': ['logarithm', 'logarithms', 'logs'],

  // Data Interpretation
  'table-charts': ['table-charts', 'table-chart', 'tables'],
  'bar-charts': ['bar-charts', 'bar-chart', 'bars'],
  'pie-charts': ['pie-charts', 'pie-chart', 'pies'],
  'line-charts': ['line-charts', 'line-chart', 'lines'],
  'caselet-di': ['caselet-di', 'caselets', 'caselet'],
  'missing-di': ['missing-di', 'missing-data'],
  'radar-web-charts': ['radar-web-charts', 'radar-charts', 'spider-charts'],
  'scatter-bubble-charts': ['scatter-bubble-charts', 'scatter-plots', 'scatter-charts'],
  'scatter-plots': ['scatter-plots', 'scatter-bubble-charts'],

  // Logical Reasoning
  'number-series': ['number-series', 'number_series'],
  'letter-and-symbol-series': ['letter-and-symbol-series', 'letter-series', 'symbol-series'],
  'verbal-classification': ['verbal-classification', 'classification'],
  'analogies': ['analogies', 'analogy'],
  'matching-definitions': ['matching-definitions', 'definitions'],
  'verbal-reasoning': ['verbal-reasoning', 'vr', 'vr-critical-reasoning'],
  'logical-games': ['logical-games', 'games'],
  'cryptarithmetic': ['cryptarithmetic', 'alphametics'],
  'machine-input-output': ['machine-input-output', 'input-output'],
  'inequalities': ['inequalities', 'coded-inequalities'],
  'order-and-ranking': ['order-and-ranking', 'ranking', 'order-ranking'],
  'floor-scheduling-puzzles': ['floor-scheduling-puzzles', 'floor-puzzles', 'scheduling-puzzles', 'puzzles'],
  'games-and-tournaments': ['games-and-tournaments', 'tournaments'],
  'truth-tellers-liars': ['truth-tellers-liars', 'binary-logic'],
  'eligibility-test': ['eligibility-test', 'decision-making'],
  'statement-and-assumption': ['statement-and-assumption', 'statement-assumption', 'assumptions'],
  'statement-and-conclusion': ['statement-and-conclusion', 'statement-conclusion', 'conclusions'],
  'cause-and-effect': ['cause-and-effect', 'cause-effect'],
  'essential-part': ['essential-part'],
  'artificial-language': ['artificial-language'],
  'making-judgments': ['making-judgments', 'judgments'],
  'logical-problems': ['logical-problems'],
  'analyzing-arguments': ['analyzing-arguments', 'arguments'],
  'course-of-action': ['course-of-action'],
  'theme-detection': ['theme-detection'],
  'statement-and-argument': ['statement-and-argument', 'statement-argument'],
  'logical-deduction': ['logical-deduction', 'deduction'],
  'logical-sequence-of-words': ['logical-sequence-of-words', 'word-sequence'],
  'syllogisms': ['syllogisms', 'syllogism'],
  'blood-relations': ['blood-relations', 'blood-relation', 'blood-relation-test', 'blood_relations'],
  'seating-arrangement': ['seating-arrangement', 'seating-arrangements', 'linear-seating', 'circular-seating', 'seating_arrangement'],
  'direction-sense': ['direction-sense', 'direction-sense-test', 'direction_sense', 'directions'],
  'cubes-and-dice': ['cubes-and-dice', 'dice', 'cube-and-cuboid', 'cubes-and-dice-nv'],

  // Verbal Ability
  'synonyms': ['synonyms', 'synonym'],
  'antonyms': ['antonyms', 'antonym'],
  'spellings': ['spellings', 'spelling-test'],
  'one-word-substitutes': ['one-word-substitutes', 'one-word-substitution'],
  'idioms-and-phrases': ['idioms-and-phrases', 'idioms', 'phrases'],
  'spotting-errors': ['spotting-errors', 'error-spotting'],
  'sentence-correction': ['sentence-correction', 'correction'],
  'sentence-improvement': ['sentence-improvement'],
  'change-of-voice': ['change-of-voice', 'active-passive-voice', 'voice'],
  'change-of-speech': ['change-of-speech', 'direct-indirect-speech', 'speech'],
  'ordering-of-words': ['ordering-of-words', 'word-order'],
  'ordering-of-sentences': ['ordering-of-sentences', 'para-jumbles', 'sentence-ordering'],
  'sentence-formation': ['sentence-formation'],
  'paragraph-formation': ['paragraph-formation'],
  'completing-statements': ['completing-statements'],
  'selecting-words': ['selecting-words'],
  'double-fillers': ['double-fillers', 'fillers'],
  'cloze-test': ['cloze-test', 'closet-test'],
  'reading-comprehension': ['reading-comprehension', 'comprehension', 'rc', 'reading_comprehension'],
  'verbal-analogies': ['verbal-analogies'],

  // Technical MCQs
  'mcq-c-programming': ['mcq-c-programming', 'c', 'c-programming', 'C_PROGRAMMING', 'c-basics'],
  'mcq-cpp-programming': ['mcq-cpp-programming', 'cpp', 'c++', 'cpp-programming', 'CPP_PROGRAMMING', 'cplusplus'],
  'mcq-java-programming': ['mcq-java-programming', 'java', 'java-programming', 'JAVA_PROGRAMMING', 'core-java'],
  'mcq-python-programming': ['mcq-python-programming', 'python', 'python-programming', 'PYTHON_PROGRAMMING'],
  'mcq-oops-concepts': ['mcq-oops-concepts', 'oops', 'oop', 'object-oriented-programming', 'SYNTAX_BASICS'],
  'mcq-database-systems': ['mcq-database-systems', 'dbms', 'sql', 'database', 'DATABASE', 'dbms-sql'],
  'mcq-operating-systems': ['mcq-operating-systems', 'os', 'operating-systems', 'OPERATING_SYSTEMS'],
  'mcq-computer-networks': ['mcq-computer-networks', 'networks', 'computer-networks', 'NETWORKING', 'cn'],
  'mcq-data-structures': ['mcq-data-structures', 'dsa', 'data-structures', 'DATA_STRUCTURES', 'dsa-logic'],
  'mcq-pseudo-code': ['mcq-pseudo-code', 'pseudo-code', 'pseudocode', 'PSEUDO_CODE', 'pseudocode-tracing'],

  // Coding Categories
  'ARRAYS': ['ARRAYS', 'POINTERS_ARRAYS', 'arrays', 'array'],
  'STRINGS': ['STRINGS', 'strings', 'string'],
  'LINKED_LISTS': ['LINKED_LISTS', 'LINEAR_STRUCTURES', 'linked-lists', 'linked_lists'],
  'STACKS_QUEUES': ['STACKS_QUEUES', 'LINEAR_STRUCTURES', 'stacks-queues', 'stacks_queues'],
  'TWO_POINTERS': ['TWO_POINTERS', 'POINTERS_ARRAYS', 'two-pointers', 'two_pointers'],
  'SLIDING_WINDOW': ['SLIDING_WINDOW', 'POINTERS_ARRAYS', 'sliding-window', 'sliding_window'],
  'TREES_BINARY_TREES': ['TREES_BINARY_TREES', 'HIERARCHICAL_STRUCTURES', 'trees', 'binary-trees'],
  'DYNAMIC_PROGRAMMING': ['DYNAMIC_PROGRAMMING', 'EXHAUSTIVE_SEARCH_DP', 'dp', 'dynamic-programming'],
  'SEARCHING_SORTING': ['SEARCHING_SORTING', 'SEARCHING', 'SEARCH_INTERVALS', 'searching-sorting'],
  'PATTERNS': ['PATTERNS', 'patterns'],
  'NUMBER_LOGIC': ['NUMBER_LOGIC', 'number-logic', 'math'],
  'RECURSION': ['RECURSION', 'recursion', 'backtracking'],
  'BIT_MANIPULATION': ['BIT_MANIPULATION', 'bit-manipulation'],
  'MATRICES': ['MATRICES', 'matrices', '2d-arrays'],
  'GRAPHS': ['GRAPHS', 'NETWORK_GRAPH_ALGORITHMS', 'graphs'],
});

/**
 * Expands an array of topic slugs into the full deduplicated set of alias variations
 */
export function expandTopicAliases(topicIds: string[]): string[] {
  if (!topicIds || topicIds.length === 0) return [];
  const result = new Set<string>();

  topicIds.forEach(id => {
    if (!id) return;
    const clean = id.trim();
    result.add(clean);
    result.add(clean.toLowerCase());

    const slug = resolveTopicSlug(clean, clean);
    result.add(slug);

    if (TOPIC_ALIAS_FAMILIES[clean]) {
      TOPIC_ALIAS_FAMILIES[clean].forEach(a => result.add(a));
    }
    if (TOPIC_ALIAS_FAMILIES[slug]) {
      TOPIC_ALIAS_FAMILIES[slug].forEach(a => result.add(a));
    }

    // Try uppercase for coding tracks
    const upper = clean.toUpperCase();
    if (TOPIC_ALIAS_FAMILIES[upper]) {
      TOPIC_ALIAS_FAMILIES[upper].forEach(a => result.add(a));
    }
  });

  return Array.from(result);
}

